# Merging The Original Datasets

In [2]:
import pandas as pd

df1 = pd.read_csv("../data/new-dataset.csv")  # contains 'track_id'
df2 = pd.read_csv("../data/original-dataset.csv")  # contains 'spotify_id'

Merging on the left, based on the Spotify ID

In [3]:
merged = pd.merge(
    df1,
    df2,
    left_on="track_id",
    right_on="spotify_id",
    how="inner"
)

In [4]:
merged

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,track,artist,seeds,number_of_emotion_tags,valence_tags,arousal_tags,dominance_tags,mbid,spotify_id,genre
0,6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.147,...,Say Something,A Great Big World,['sad'],7,2.887157,3.535294,4.034216,4a88e54b-3fd9-4d99-9787-ea2853cfbba1,6Vc5wAMmXdKIAM7WUoEb7N,indie pop
1,8,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,0.414,...,Lucky,Jason Mraz,"['romantic', 'sweet']",10,7.779724,4.980663,6.143867,f68a7497-91aa-4d8a-88c8-abc0ba5b49f7,0IktbUcnAGrvD03AWnz3Q8,acoustic
2,15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,...,Falling In Love At A Coffee Shop,Landon Pigg,"['soothing', 'romantic', 'sweet', 'calm']",20,7.004538,3.695087,6.201908,614a39e0-ebe9-453c-8dc4-e004676c345b,1KHdq8NK9QxnGjdXb55NiG,acoustic
3,15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,...,Coffee Shop,Landon Pigg,['thoughtful'],4,7.364104,4.021567,6.479030,NaN,1KHdq8NK9QxnGjdXb55NiG,indie
4,53,5JDcQAztvZTIkrWoZihgvC,Ron Pope,The Bedroom Demos,A Drop in the Ocean,68,220239,False,0.447,0.393,...,A Drop In The Ocean,Ron Pope,['romantic'],14,7.275094,4.950283,5.977500,9b347a38-772d-4019-b5ff-eeacd31109e3,5JDcQAztvZTIkrWoZihgvC,piano
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1713,111976,6WDAtzaXY7d31CkuoxYFcb,Little Dragon,Machine Dreams,Feather,53,293786,False,0.663,0.831,...,Feather,Little Dragon,"['dreamy', 'erotic', 'sensual', 'spacey']",14,5.982339,4.706129,5.713065,05ff6859-d7e9-4ade-b881-ba1310c806ba,6WDAtzaXY7d31CkuoxYFcb,electronic
1714,113234,6qdpQ6jPiaCYE9Qw4nZVuD,Tenth Avenue North,Over And Underneath,By Your Side,54,241826,False,0.454,0.700,...,By Your Side,Tenth Avenue North,['uplifting'],8,6.519419,4.181860,6.036163,ab853ef3-17f8-47dd-bf39-8778a98a30be,6qdpQ6jPiaCYE9Qw4nZVuD,christian rock
1715,113492,7j1e730A8K1my1mM4knYmr,Chris Tomlin,How Great Is Our God: The Essential Collection,I Will Rise,47,300373,False,0.213,0.320,...,I Will Rise,Chris Tomlin,['soothing'],3,5.416471,3.337647,4.507059,5b3f1b06-ec8c-43d1-a2cf-0413a84c2f3d,7j1e730A8K1my1mM4knYmr,worship
1716,113497,3CO19cTl5zzlWx9GWEpOhD,Michael W. Smith,Change Your World,I Will Be Here For You,53,273773,False,0.425,0.519,...,I Will Be Here For You,Michael W. Smith,['spiritual'],4,6.135000,4.251765,5.960294,5637873b-fe19-4e3a-90bb-f5e6d29b5fd1,3CO19cTl5zzlWx9GWEpOhD,pop
1717,113564,3stuliHpnexsTj6uXFJ5iI,Audrey Assad,The House You're Building,Restless,47,295064,False,0.422,0.377,...,Restless,Audrey Assad,['light'],2,7.150000,4.085000,6.530000,0839e7bb-651d-4c6b-88b6-3f8c2311a43f,3stuliHpnexsTj6uXFJ5iI,NaN

Dropping NA for empty genres

In [5]:
merged.dropna(subset=["genre"], inplace=True)

In [6]:
merged

,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,track,artist,seeds,number_of_emotion_tags,valence_tags,arousal_tags,dominance_tags,mbid,spotify_id,genre
0,6,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.147,...,Say Something,A Great Big World,['sad'],7,2.887157,3.535294,4.034216,4a88e54b-3fd9-4d99-9787-ea2853cfbba1,6Vc5wAMmXdKIAM7WUoEb7N,indie pop
1,8,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,0.414,...,Lucky,Jason Mraz,"['romantic', 'sweet']",10,7.779724,4.980663,6.143867,f68a7497-91aa-4d8a-88c8-abc0ba5b49f7,0IktbUcnAGrvD03AWnz3Q8,acoustic
2,15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,...,Falling In Love At A Coffee Shop,Landon Pigg,"['soothing', 'romantic', 'sweet', 'calm']",20,7.004538,3.695087,6.201908,614a39e0-ebe9-453c-8dc4-e004676c345b,1KHdq8NK9QxnGjdXb55NiG,acoustic
3,15,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,...,Coffee Shop,Landon Pigg,['thoughtful'],4,7.364104,4.021567,6.479030,NaN,1KHdq8NK9QxnGjdXb55NiG,indie
4,53,5JDcQAztvZTIkrWoZihgvC,Ron Pope,The Bedroom Demos,A Drop in the Ocean,68,220239,False,0.447,0.393,...,A Drop In The Ocean,Ron Pope,['romantic'],14,7.275094,4.950283,5.977500,9b347a38-772d-4019-b5ff-eeacd31109e3,5JDcQAztvZTIkrWoZihgvC,piano
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,111908,25G1w3E4OMrovtPE5F510g,Portishead,Portishead,Undenied,46,260026,False,0.241,0.281,...,Undenied,Portishead,['sad'],11,3.990364,3.556909,4.318909,54727d71-8789-407c-a622-3e1acf01e178,25G1w3E4OMrovtPE5F510g,trip-hop
1713,111976,6WDAtzaXY7d31CkuoxYFcb,Little Dragon,Machine Dreams,Feather,53,293786,False,0.663,0.831,...,Feather,Little Dragon,"['dreamy', 'erotic', 'sensual', 'spacey']",14,5.982339,4.706129,5.713065,05ff6859-d7e9-4ade-b881-ba1310c806ba,6WDAtzaXY7d31CkuoxYFcb,electronic
1714,113234,6qdpQ6jPiaCYE9Qw4nZVuD,Tenth Avenue North,Over And Underneath,By Your Side,54,241826,False,0.454,0.700,...,By Your Side,Tenth Avenue North,['uplifting'],8,6.519419,4.181860,6.036163,ab853ef3-17f8-47dd-bf39-8778a98a30be,6qdpQ6jPiaCYE9Qw4nZVuD,christian rock
1715,113492,7j1e730A8K1my1mM4knYmr,Chris Tomlin,How Great Is Our God: The Essential Collection,I Will Rise,47,300373,False,0.213,0.320,...,I Will Rise,Chris Tomlin,['soothing'],3,5.416471,3.337647,4.507059,5b3f1b06-ec8c-43d1-a2cf-0413a84c2f3d,7j1e730A8K1my1mM4knYmr,worship
1716,113497,3CO19cTl5zzlWx9GWEpOhD,Michael W. Smith,Change Your World,I Will Be Here For You,53,273773,False,0.425,0.519,...,I Will Be Here For You,Michael W. Smith,['spiritual'],4,6.135000,4.251765,5.960294,5637873b-fe19-4e3a-90bb-f5e6d29b5fd1,3CO19cTl5zzlWx9GWEpOhD,pop

Remove unused columns

In [7]:
merged.drop(columns=['Unnamed: 0'], inplace=True)

In [8]:
merged

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,...,track_genre,lastfm_url,seeds,number_of_emotion_tags,valence_tags,arousal_tags,dominance_tags,mbid,spotify_id,genre
0,6Vc5wAMmXdKIAM7WUoEb7N,A Great Big World;Christina Aguilera,Is There Anybody Out There?,Say Something,74,229400,False,0.407,0.147,2,...,acoustic,https://www.last.fm/music/a%2bgreat%2bbig%2bwo...,['sad'],7,2.887157,3.535294,4.034216,4a88e54b-3fd9-4d99-9787-ea2853cfbba1,6Vc5wAMmXdKIAM7WUoEb7N,indie pop
1,0IktbUcnAGrvD03AWnz3Q8,Jason Mraz;Colbie Caillat,We Sing. We Dance. We Steal Things.,Lucky,74,189613,False,0.625,0.414,0,...,acoustic,https://www.last.fm/music/jason%2bmraz/_/lucky,"['romantic', 'sweet']",10,7.779724,4.980663,6.143867,f68a7497-91aa-4d8a-88c8-abc0ba5b49f7,0IktbUcnAGrvD03AWnz3Q8,acoustic
2,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,4,...,acoustic,https://www.last.fm/music/landon%2bpigg/_/fall...,"['soothing', 'romantic', 'sweet', 'calm']",20,7.004538,3.695087,6.201908,614a39e0-ebe9-453c-8dc4-e004676c345b,1KHdq8NK9QxnGjdXb55NiG,acoustic
3,1KHdq8NK9QxnGjdXb55NiG,Landon Pigg,The Boy Who Never,Falling in Love at a Coffee Shop,58,244986,False,0.489,0.561,4,...,acoustic,https://www.last.fm/music/landon%2bpigg/_/coff...,['thoughtful'],4,7.364104,4.021567,6.479030,NaN,1KHdq8NK9QxnGjdXb55NiG,indie
4,5JDcQAztvZTIkrWoZihgvC,Ron Pope,The Bedroom Demos,A Drop in the Ocean,68,220239,False,0.447,0.393,5,...,acoustic,https://www.last.fm/music/ron%2bpope/_/a%2bdro...,['romantic'],14,7.275094,4.950283,5.977500,9b347a38-772d-4019-b5ff-eeacd31109e3,5JDcQAztvZTIkrWoZihgvC,piano
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,25G1w3E4OMrovtPE5F510g,Portishead,Portishead,Undenied,46,260026,False,0.241,0.281,0,...,trip-hop,https://www.last.fm/music/portishead/_/undenied,['sad'],11,3.990364,3.556909,4.318909,54727d71-8789-407c-a622-3e1acf01e178,25G1w3E4OMrovtPE5F510g,trip-hop
1713,6WDAtzaXY7d31CkuoxYFcb,Little Dragon,Machine Dreams,Feather,53,293786,False,0.663,0.831,2,...,trip-hop,https://www.last.fm/music/little%2bdragon/_/fe...,"['dreamy', 'erotic', 'sensual', 'spacey']",14,5.982339,4.706129,5.713065,05ff6859-d7e9-4ade-b881-ba1310c806ba,6WDAtzaXY7d31CkuoxYFcb,electronic
1714,6qdpQ6jPiaCYE9Qw4nZVuD,Tenth Avenue North,Over And Underneath,By Your Side,54,241826,False,0.454,0.700,7,...,world-music,https://www.last.fm/music/tenth%2bavenue%2bnor...,['uplifting'],8,6.519419,4.181860,6.036163,ab853ef3-17f8-47dd-bf39-8778a98a30be,6qdpQ6jPiaCYE9Qw4nZVuD,christian rock
1715,7j1e730A8K1my1mM4knYmr,Chris Tomlin,How Great Is Our God: The Essential Collection,I Will Rise,47,300373,False,0.213,0.320,11,...,world-music,https://www.last.fm/music/chris%2btomlin/_/i%2...,['soothing'],3,5.416471,3.337647,4.507059,5b3f1b06-ec8c-43d1-a2cf-0413a84c2f3d,7j1e730A8K1my1mM4knYmr,worship
1716,3CO19cTl5zzlWx9GWEpOhD,Michael W. Smith,Change Your World,I Will Be Here For You,53,273773,False,0.425,0.519,9,...,world-music,https://www.last.fm/music/michael%2bw.%2bsmith...,['spiritual'],4,6.135000,4.251765,5.960294,5637873b-fe19-4e3a-90bb-f5e6d29b5fd1,3CO19cTl5zzlWx9GWEpOhD,pop

In [9]:
merged.to_csv("output.csv")